"""Fabrication package export: gerbers, drill, positions, notes, zip.

A DRC-clean ``.kicad_pcb`` is one step away from an orderable archive
(hardening plan 3.1). This module drives ``kicad-cli pcb export`` for the
industry-standard outputs and bundles them with generated fab notes.
Packaging adds no new truth: the authority statuses are unchanged.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

from pcbsmith.kicad.cli import KiCadInstall, KiCadProcessResult, find_kicad_cli


class FabricationError(RuntimeError):
    pass


@dataclass(frozen=True)
class FabPackage:
    zip_file: Path
    files: tuple[str, ...]
    notes_file: Path


def _default_runner(command: Sequence[str]) -> KiCadProcessResult:
    completed = subprocess.run(
        list(command), capture_output=True, text=True, check=False
    )
    return KiCadProcessResult(
        command=tuple(command),
        returncode=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
    )


def _board_facts(board_file: Path) -> dict[str, str]:
    text = board_file.read_text(encoding="utf-8")
    facts: dict[str, str] = {}
    xs: list[float] = []
    ys: list[float] = []
    edge_section = re.findall(
        r"\(gr_(?:poly|line|rect|arc|circle)[^“]*?\(layer \"Edge.Cuts\"\)", text
    )
    for x, y in re.findall(r"\(xy (-?\d+\.?\d*) (-?\d+\.?\d*)\)", text):
        xs.append(float(x))
        ys.append(float(y))
    if xs and ys:
        facts["extent_mm"] = (
            f"{max(xs) - min(xs):.1f} x {max(ys) - min(ys):.1f}"
        )
    facts["copper_layers"] = "2"
    facts["has_mask_opening"] = (
        "yes" if '(layer "F.Mask")' in text and "(gr_poly" in text else "no"
    )
    facts["edge_items"] = str(len(edge_section))
    return facts


def _fab_notes(project_name: str, facts: dict[str, str]) -> str:
    lines = [
        f"# Fabrication notes: {project_name}",
        "",
        f"- Copper layers: {facts.get('copper_layers', '2')}",
        f"- Board extent (all drawn geometry): {facts.get('extent_mm', 'see gerbers')} mm",
        "- Material: FR-4, 1.6 mm, 1 oz outer copper.",
        "- Minimum track/clearance used by the design rules: 0.2 mm.",
    ]
    if facts.get("has_mask_opening") == "yes":
        lines.extend(
            (
                "- This board EXPOSES copper through soldermask openings by "
                "design (functional sensing copper).",
                "- Specify ENIG surface finish: exposed copper is functional "
                "and HASL leveling or bare copper would degrade or corrode.",
            )
        )
    lines.extend(
        (
            "",
            "Generated by PCBSmith. The design has passed KiCad ERC, DRC "
            "with schematic parity, and behavioral simulation; it still "
            "carries a needs-human-review status by policy.",
            "",
        )
    )
    return "\n".join(lines)


def export_fab_package(
    board_file: Path,
    *,
    project_name: str,
    finder: Callable[[], KiCadInstall | None] = find_kicad_cli,
    runner: Callable[[Sequence[str]], KiCadProcessResult] | None = None,
) -> FabPackage:
    install = finder()
    if install is None:
        raise FabricationError("KiCad CLI was not found; cannot export gerbers.")
    run = runner or _default_runner

    fab_dir = board_file.parent / "fab"
    work_dir = fab_dir / "files"
    if work_dir.exists():
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True)

    commands: tuple[tuple[str, tuple[str, ...]], ...] = (
        (
            "gerbers",
            (
                str(install.path), "pcb", "export", "gerbers",
                "--output", str(work_dir) + "\\",
                str(board_file),
            ),
        ),
        (
            "drill",
            (
                str(install.path), "pcb", "export", "drill",
                "--format", "excellon",
                "--generate-map", "--map-format", "gerberx2",
                "--output", str(work_dir) + "\\",
                str(board_file),
            ),
        ),
        (
            "positions",
            (
                str(install.path), "pcb", "export", "pos",
                "--format", "csv", "--units", "mm", "--side", "both",
                "--output", str(work_dir / f"{project_name}-positions.csv"),
                str(board_file),
            ),
        ),
    )
    for label, command in commands:
        result = run(command)
        if result.returncode != 0:
            raise FabricationError(
                f"kicad-cli {label} export failed: "
                f"{result.stderr.strip() or result.stdout.strip()}"
            )

    notes_file = work_dir / "fab-notes.md"
    notes_file.write_text(
        _fab_notes(project_name, _board_facts(board_file)), encoding="utf-8"
    )

    files = tuple(sorted(path.name for path in work_dir.iterdir()))
    if len(files) < 5:
        raise FabricationError(
            f"Fab export produced only {len(files)} files; expected gerber "
            "layers, drill, positions, and notes."
        )
    zip_base = fab_dir / f"{project_name}-fab"
    zip_path = Path(
        shutil.make_archive(str(zip_base), "zip", root_dir=work_dir)
    )
    return FabPackage(zip_file=zip_path, files=files, notes_file=notes_file)
