from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path
from uuid import uuid4

from pcbsmith.services.kicad_backend import find_kicad_cli
from pcbsmith.services.kicad_board_builder import (
    KiCadBoardBuilder,
    NetRef,
    TwoPadSmdFootprintSpec,
)
from pcbsmith.services.kicad_preview import (
    format_kicad_preview_report,
    run_kicad_preview,
)
from pcbsmith.services.kicad_project import (
    render_kicad_project_file,
    render_kicad_schematic_file,
    sanitize_kicad_project_name,
)
from pcbsmith.services.kicad_validate import (
    format_kicad_validation_report,
    run_kicad_validation,
)
from pcbsmith.services.led_art import (
    LedArtPixel,
    LedArtPlan,
    LedArtSpec,
    build_led_art_plan,
    write_led_art_reports,
)

BOARD_WIDTH_MM = 420.0
BOARD_HEIGHT_MM = 120.0
VCC_RAIL_Y_MM = 8.0
GND_RAIL_Y_MM = 108.0
TRACE_WIDTH_MM = 0.45
SOURCE_LOGO_SVG = Path("D:/VIR LAB/VEKTOR-04.svg")
SOURCE_LOGO_PNG = Path("D:/VIR LAB/1-04.png")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a KiCad VIR-LAB 5V 0603 LED demo board."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(".tmp/vir-lab-led-demo-20260511-01/kicad-review"),
        help="Output KiCad project directory.",
    )
    parser.add_argument("--name", default="VIR LAB 5V LED Demo")
    parser.add_argument(
        "--no-polarity-marks",
        action="store_true",
        help="omit educational LED anode + marks from the board silkscreen",
    )
    args = parser.parse_args()

    project_dir = args.output
    _reset_output_dir(project_dir)
    project_name = sanitize_kicad_project_name(args.name)
    project_dir.mkdir(parents=True)

    plan = build_led_art_plan(LedArtSpec(text="VIR-LAB"))
    project_file = project_dir / f"{project_name}.kicad_pro"
    schematic_file = project_dir / f"{project_name}.kicad_sch"
    board_file = project_dir / f"{project_name}.kicad_pcb"

    project_file.write_text(render_kicad_project_file(project_name), encoding="utf-8")
    schematic_file.write_text(
        render_kicad_schematic_file(uuid4()),
        encoding="utf-8",
    )
    board_file.write_text(
        _render_board(plan, show_polarity_marks=not args.no_polarity_marks),
        encoding="utf-8",
    )
    _copy_logo_sources(project_dir)
    _write_layout_first_readme(project_dir, project_name, plan)
    write_led_art_reports(plan, project_dir / ".pcbsmith" / "reports")

    validation = run_kicad_validation(project_dir)
    preview = run_kicad_preview(project_dir)
    schematic_note_paths = _replace_blank_schematic_svgs(project_dir, project_name, plan)
    assembly_preview = _export_assembly_preview(project_dir, project_name, board_file)
    print("\n".join(format_kicad_validation_report(validation)))
    print("\n".join(format_kicad_preview_report(preview)))
    for note_path in schematic_note_paths:
        print(f"Layout-first schematic note SVG: {note_path}")
    if assembly_preview is not None:
        print(f"Assembly preview SVG: {assembly_preview}")
    if validation.exit_code or preview.exit_code:
        raise SystemExit(1)


def _reset_output_dir(project_dir: Path) -> None:
    resolved = project_dir.resolve()
    workspace = Path.cwd().resolve()
    if not resolved.is_relative_to(workspace):
        raise ValueError(f"Output must be inside the workspace: {project_dir}")
    if resolved.exists():
        shutil.rmtree(resolved)


def _copy_logo_sources(project_dir: Path) -> None:
    assets_dir = project_dir / ".pcbsmith" / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    for source in (SOURCE_LOGO_SVG, SOURCE_LOGO_PNG):
        if source.exists():
            shutil.copyfile(source, assets_dir / source.name)


def _write_layout_first_readme(
    project_dir: Path,
    project_name: str,
    plan: LedArtPlan,
) -> None:
    readme = project_dir / "README.md"
    readme.write_text(
        "\n".join(
            [
                f"# {project_name}",
                "",
                "This is a PCB-layout-first KiCad demo generated by PCBSmith.",
                "",
                "- The board contains the routed 5V VIR-LAB LED layout.",
                "- Each 0603 LED has its own "
                f"{plan.electrical.resistor_value_ohms} ohm 0603 resistor.",
                "- The electrical report estimates current draw and flags "
                "input-power budget warnings.",
                "- The KiCad schematic is intentionally minimal in this demo.",
                "- Full schematic array and hierarchy generation is a later PCBSmith slice.",
                "- Use the board SVG, assembly preview SVG, Gerbers, and laser F.Cu SVG "
                "for review.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _replace_blank_schematic_svgs(
    project_dir: Path,
    project_name: str,
    plan: LedArtPlan,
) -> list[Path]:
    visual_dir = project_dir / ".pcbsmith" / "visual"
    note_svg = _layout_first_schematic_note_svg(project_name, plan)
    paths = [
        visual_dir / f"{project_name}-schematic.svg",
        visual_dir / f"{project_name}.svg",
        visual_dir / ".work" / "schematic" / f"{project_name}.svg",
    ]
    written_paths: list[Path] = []
    for path in paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(note_svg, encoding="utf-8")
        written_paths.append(path)
    return written_paths


def _layout_first_schematic_note_svg(project_name: str, plan: LedArtPlan) -> str:
    resistor_value = plan.electrical.resistor_value_ohms
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" width="900" height="320" viewBox="0 0 900 320">
  <rect width="900" height="320" fill="#fffef8"/>
  <text x="40" y="70" font-family="Arial, sans-serif" font-size="28" fill="#006464">
    {project_name}
  </text>
  <text x="40" y="125" font-family="Arial, sans-serif" font-size="20" fill="#222">
    Layout-first PCB demo: schematic array generation is intentionally deferred.
  </text>
  <text x="40" y="170" font-family="Arial, sans-serif" font-size="18" fill="#222">
    Review the KiCad PCB, board SVG, assembly preview SVG, Gerbers, and laser F.Cu SVG.
  </text>
  <text x="40" y="215" font-family="Arial, sans-serif" font-size="18" fill="#222">
    Circuit intent: 5V input, one {resistor_value} ohm resistor per red 0603 LED pixel.
  </text>
</svg>
"""


def _export_assembly_preview(
    project_dir: Path,
    project_name: str,
    board_file: Path,
) -> Path | None:
    install = find_kicad_cli()
    if install is None:
        return None

    output_file = project_dir / ".pcbsmith" / "visual" / f"{project_name}-assembly.svg"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    completed = subprocess.run(
        [
            str(install.cli_path),
            "pcb",
            "export",
            "svg",
            "--output",
            str(output_file),
            "--layers",
            "F.Cu,F.Fab,F.SilkS,Edge.Cuts",
            "--page-size-mode",
            "2",
            "--fit-page-to-board",
            "--exclude-drawing-sheet",
            "--mode-single",
            str(board_file),
        ],
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        message = completed.stderr.strip() or completed.stdout.strip()
        raise RuntimeError(f"Assembly preview export failed: {message}")
    return output_file


def _render_board(plan: LedArtPlan, *, show_polarity_marks: bool) -> str:
    builder = KiCadBoardBuilder()
    pixels = plan.pixels
    net_refs = {name: builder.net(name) for name in ["VCC", "GND"]}
    for pixel in pixels:
        net_refs[pixel.drive_net] = builder.net(pixel.drive_net)

    _add_silkscreen(builder, plan)
    _add_power_pads(builder, net_refs)
    _add_power_rails(builder, net_refs, pixels)
    for pixel in pixels:
        _add_resistor(builder, pixel, net_refs, plan.electrical.resistor_value_ohms)
        _add_led(builder, pixel, net_refs, show_polarity_marks=show_polarity_marks)
        _add_pixel_tracks(builder, pixel, net_refs)
    return builder.render(outline_end_mm=(BOARD_WIDTH_MM, BOARD_HEIGHT_MM))


def _add_power_pads(builder: KiCadBoardBuilder, net_refs: dict[str, NetRef]) -> None:
    builder.add_power_pad(
        "VCC",
        7.0,
        VCC_RAIL_Y_MM,
        net=net_refs["VCC"],
        value="5V Input",
        reference_offset_mm=(-4.0, 0.0),
    )
    builder.add_power_pad(
        "GND",
        7.0,
        12.0,
        net=net_refs["GND"],
        value="5V Input",
        reference_offset_mm=(-4.0, 0.0),
    )


def _add_power_rails(
    builder: KiCadBoardBuilder,
    net_refs: dict[str, NetRef],
    pixels: tuple[LedArtPixel, ...],
) -> None:
    last_vcc_tap_x = max(pixel.vcc_tap_x for pixel in pixels)
    last_gnd_tap_x = max(pixel.gnd_tap_x for pixel in pixels)
    builder.add_segment(
        7.0,
        VCC_RAIL_Y_MM,
        last_vcc_tap_x,
        VCC_RAIL_Y_MM,
        width_mm=TRACE_WIDTH_MM,
        net=net_refs["VCC"],
    )
    builder.add_segment(
        7.0,
        GND_RAIL_Y_MM,
        last_gnd_tap_x,
        GND_RAIL_Y_MM,
        width_mm=TRACE_WIDTH_MM,
        net=net_refs["GND"],
    )
    builder.add_segment(
        7.0,
        12.0,
        7.0,
        GND_RAIL_Y_MM,
        width_mm=TRACE_WIDTH_MM,
        net=net_refs["GND"],
    )


def _add_pixel_tracks(
    builder: KiCadBoardBuilder,
    pixel: LedArtPixel,
    net_refs: dict[str, NetRef],
) -> None:
    builder.add_segment(
        pixel.vcc_tap_x,
        VCC_RAIL_Y_MM,
        pixel.vcc_tap_x,
        pixel.y,
        width_mm=TRACE_WIDTH_MM,
        net=net_refs["VCC"],
    )
    builder.add_segment(
        pixel.x - 1.05,
        pixel.y,
        pixel.x + 1.05,
        pixel.y,
        width_mm=TRACE_WIDTH_MM,
        net=net_refs[pixel.drive_net],
    )
    builder.add_segment(
        pixel.gnd_tap_x,
        pixel.y,
        pixel.gnd_tap_x,
        GND_RAIL_Y_MM,
        width_mm=TRACE_WIDTH_MM,
        net=net_refs["GND"],
    )


def _add_resistor(
    builder: KiCadBoardBuilder,
    pixel: LedArtPixel,
    net_refs: dict[str, NetRef],
    resistor_value_ohms: int,
) -> None:
    builder.add_two_pad_smd_footprint(
        TwoPadSmdFootprintSpec(
            footprint="PCBSmith_R_0603_REAL",
            reference=pixel.resistor_ref,
            value=str(resistor_value_ohms),
            x_mm=pixel.resistor_x,
            y_mm=pixel.y,
            left_net=net_refs["VCC"],
            right_net=net_refs[pixel.drive_net],
            reference_offset_mm=(0.0, -2.0),
        )
    )


def _add_led(
    builder: KiCadBoardBuilder,
    pixel: LedArtPixel,
    net_refs: dict[str, NetRef],
    *,
    show_polarity_marks: bool,
) -> None:
    builder.add_two_pad_smd_footprint(
        TwoPadSmdFootprintSpec(
            footprint="PCBSmith_LED_0603_REAL",
            reference=pixel.led_ref,
            value="Red 0603",
            x_mm=pixel.led_x,
            y_mm=pixel.y,
            left_net=net_refs[pixel.drive_net],
            right_net=net_refs["GND"],
            reference_offset_mm=(0.0, -2.0),
            silk_marker="cathode",
            show_anode_plus=show_polarity_marks,
        )
    )


def _add_silkscreen(builder: KiCadBoardBuilder, plan: LedArtPlan) -> None:
    builder.add_text("VIR-LAB 5V LED TEST", 180, 5, size_mm=2.0)
    builder.add_text(
        f"0603 LEDs, {plan.electrical.resistor_value_ohms}R per LED",
        180,
        114,
        size_mm=1.2,
    )
    builder.add_text("VIR", 382, 88, size_mm=4.0)
    builder.add_text("LAB", 382, 97, size_mm=4.0)
    builder.add_rect(366, 78, 412, 108)

if __name__ == "__main__":
    main()
